# Generated by Django 3.1.7 on 2021-03-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20210305_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='sin-categorizar', max_length=30),
        ),
    ]
